# Generated by Django 5.2.8 on 2025-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('security', 'Security'), ('secretary', 'Secretary'), ('flat_owner', 'Flat Owner')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
